### ISSUE TITLE
Figure out Hard Bounce Issue between Keystone and Mail Chimp

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#380] opened 2019-11-07 21:34 UTC
@jeremysMARE researched issue with tagging manual subscribers in mailchimp and identified that he is unable to subscribe some social workers b/c they previously had a hard bounce from their known email and thus were cleaned by mailchimp.  The only way to resolve this is to have the user fill out a form to resubscribe to each list, which is a big challenge for us.

We need noah to explore the following:
1.) Did deeper into the why these email addresses are having a hard bounce.
2.) If we were to get users to resubscribe, what would prevent this from continuing to happen?
3.) If a user gets wiped clean in mail chimp, is it circling back and deleting their subscription preferences in Keystone?
4.) Potentially figure out how to get around DCF's spam filters if this is indeed the reason why some emails are getting hard bounce
5.) explore options for sending emails in batchs as possible solution to avoid hard bounce in the future

**Comment by joesmare** [comment] 2019-11-20 15:19
Hold on global resolution.

@n-devr will investigate the process by which keystone email changes are reflected at MailChimp. Provide a resolution that includes IDing changes at Keystone to reflect the change on the MailChimp list.

**Comment by jeremysMARE** [comment] 2019-11-21 16:31
[MailChimp - Keystone Comparison.xlsx](https://github.com/mareinc/mare/files/3875705/MailChimp.-.Keystone.Comparison.xlsx)
I'm attaching an excel sheet that shows the disparity between MailChimp's list of subscribed social workers and Keystone's list of subscribed social workers.

**Comment by n-devr** [comment] 2019-11-21 16:46
Based on our discussion/investigation yesterday there are two tasks on my plate:

- [ ] Update email address in Mailchimp if a user updates their email in Keystone
- [ ] Run a script to update the subscription preferences of the social workers in Jeremy's list

@joesmare @bchiaruttini  please let me know if there's anything else you'd like me to tackle as part of this story!

**Comment by joesmare** [comment] 2019-11-21 16:49
Yes @n-devr those are the actions required. I'm ruling out other external factors at this point. If there are any future issues I'll open a new story should we need to look at other related issues? 

Thank you for all of your insight and input. I appreciate it. Glad you are on the team.

**Comment by n-devr** [comment] 2019-11-21 17:03
Sounds good @joesmare , thank you!  Happy help and happy to be part of the team 😄

**Comment by n-devr** [comment] 2019-11-22 20:55
I've added logic in Keystone to update a user's email address in Mailchimp if they update their email address in Keystone, so that should take care of any issues with users getting out of sync when they change their email.

Now I'm looking into creating a script to sync the subscription statuses of the social workers in the list that @jeremysMARE provided, but I'm a little confused.  From the checks that I've done (just randomly picking an email from the list), none of those social workers exist in the Keystone database.  Is that your expectation @bchiaruttini and @joesmare ?  I thought these were all social workers that existed in Keystone but did not have their mailing list preferences synced with their actual subscriptions in Mailchimp.  I think I must have missed something 🤷‍♂

**Comment by joesmare** [comment] 2019-11-25 14:25
@n-devr there is one specific use case that I want to be sure to include in this work. In conversation with Bridget this morning we discussed that staff are sometimes creating records (as we've discussed as part of this work in the past) and that when someone creates a record from the admin UI they don't get the mailing list elections. Since Opt-In is the protocol I assume that the code would replicate the behavior of adding them to all three mailing lists, but have not tested this directly. Before I go down a rabbit hole, can you think about the code side of things and confirm or deny that a new user (any type) created by an admin. will be automatically subscribed to the lists? TY-we can discuss further on our call, as needed.

**Comment by joesmare** [comment] 2019-11-25 19:08
As discussed @n-devr the staff will use front-end form for creating ANY new accounts. DO NOT create a new record on the back-end.

**Comment by joesmare** [comment] 2019-11-25 19:59
@jeremysMARE did you check the other user types (aside from SW) to see if the initial code missed any other groups? We will need to run the clean-up on any other lists that may have chunks of missing tags as well. Please report back to @joesmare with any additional findings. There is a use case specific use case with SW-Waluszko (this is an example of a wrongly tagged SW-tagged as Homestudy registered in MailChimp)

@n-devr and @jeremysMARE please work together to pull lists to assure that we've caught these issues across all populations. Also, schedule quarterly/semi-annual audits to assure that this stays in sync.

**Comment by n-devr** [comment] 2019-11-25 20:06
While testing with Joe I realized that the social workers that @jeremysMARE compiled into a list _do_ in fact exist in Keystone - you just can't search for users by their email address.  That was my misunderstanding - Jeremy the list is accurate and I will write a script to ensure their email preferences are captured properly on the Keystone side.

**Comment by n-devr** [comment] 2019-12-03 20:38
Is it possible that the subscription statuses of the social workers have changed since the Excel spreadsheet was generated?  I started writing a script to run through the list, but I'm noticing that many of them are subscribed to at least one, if not all three, of the Mailchimp mailing lists.

**Comment by bchiaruttini** [comment] 2019-12-04 12:41
@n-devr @jeremysMARE  Yes I do think Jeremy manually tagged some workers as SW in mail chimp since that spreadsheet was first run.

**Comment by n-devr** [comment] 2019-12-04 17:42
I went through the updated list of active Social Workers who weren't subscribed to any Mailchimp mailing lists and updated any of them that had valid emails and had somehow gotten out of sync.  Attached is a list of the social workers that I could not update for some reason or another.
[Social Workers Missing From Mailchimp.xlsx](https://github.com/mareinc/mare/files/3923229/Social.Workers.Missing.From.Mailchimp.xlsx)

**Comment by joesmare** [comment] 2019-12-05 13:20
@n-devr  thank you for all of your help researching and correcting this issue. The final list of 40+/- workers with missing emails, unidentifiable issues, etc. is a an acceptable exceptions list. I understand that in your research you determined that there were a number of records that appear to have been corrected in Keystone without any explanation. As such, you did not end-up writing code to support this process. Rather, you fixed them manually due to the low volume (as it was more efficient). 
We will close this story, but not assume that the issue is fully resolved until we have several future opportunities to validate that the data is staying in sync between MailChimp and Keystone. 
To that end, @jeremysMARE will run list sync checks between either the MM or Event lists and Keystone, once every 30 days. He will report any discrepancies back through this team to allow for further exploration of possible causes. If no out of sync record issues are observed over several cycles we will then consider this issue fully closed. 
Moving this to a new story for @jeremysMARE..

**Closed by joesmare** 2019-12-05 13:20 UTC
Labels: emails, integrations, model updates needed - production, ready to test - production
