### ISSUE TITLE
Change of Social Worker/Agency at Family User Account Level

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#406] opened 2020-01-08 17:54 UTC
When a logged-in family looks at their My Record in Keystone they cannot see the SW/agency/SW contact info. (These are open text fields at the time of account creation, which MARE staff then manually enter into family record.)  However it appears blank in My Account even when visible in admin UI. 

When a registered family tries to submit a new SW/agency/SW contact info. by entering it in the 'Social Worker Name' field, in their record, it generates a "red box error".  (BC did not get this error in testing on 3/2021, but did 4/2021)  Data saved during that session, but not there when user returns.  Did not trigger an email of changes to Family Support Services. 

To solve: My Account should pull existing information if entered from admin UI (if entered)  If family updates, it should generate email recording changes to MARE staff person for manual change.  (If this is not possible or too complicated, could add instructions to user that in order to update their worker/contact info, email ricardof@mareinc.org with automated email with prescribed forms)

**Comment by joesmare** [comment] 2020-01-09 17:19
@bchiaruttini when you have a second, can you review this to make sure that the requested action meets the standards that we discussed? TY

**Comment by joesmare** [comment] 2020-01-10 20:26
I just need an estimate on the amount of time that this project will take. I will make a decision about whether or not we will proceed, based upon the estimate. TY

**Comment by n-devr** [comment] 2020-01-15 15:41
Possible dupe of #165 ?

**Comment by bchiaruttini** [comment] 2020-01-15 16:45
@n-devr @joesmare Yes, definitely a dupe.  Let's stick with 406 as more detail.

**Comment by n-devr** [comment] 2021-04-28 15:20
Most of the fields on the page will automatically update in Keystone when changed by a family.  Is this still the desired behavior?  E.g. the family can update their Homestudy Completed status without any oversight from MARE.

Seems like we may need to go through the form and determine which fields are 'self-serve' and which fields should generate an email to be reviewed by MARE before being set in Keystone.

**Comment by bchiaruttini** [comment] 2021-04-28 18:12
Yes, okay to update all other fields automatically but lets discuss simplifying this one.

Q: What happens if they change their email in terms of email verification process?

**Comment by n-devr** [comment] 2021-04-28 20:37
Per discussion with Bridget:
- [ ] Remove SW phone and email fields
- [ ] Ensure SW name and agency fields are pulled from record, but make them read-only
- [ ] Update copy in Homestudy Details section to include instructions for requesting a SW update via email

**Comment by bchiaruttini** [comment] 2021-04-28 20:57
Decided today that we will allow user to view-only any SW information that is already entered into their account but to make changes will need to email us.  Please change the section in My Information called Homestudy Details to read:

Date Homestudy Completed/Updated:
Social Worker Name:
To make updates to this information, or to send us your approved homestudy for matching (MA families only), please email us: 

Send as email (button)

**Comment by n-devr** [comment] 2021-04-29 18:05
Updates are live in `develop` and ready for review.

I noticed that the `Date Homestudy Completed/Updated` field has a similar behavior to the Social Worker fields we just updated - it doesn't pull the Date from the Family record and allows users to enter data but doesn't do anything with that data.  Should I also update that field to be a read-only display of the the data currently in the Family record?

**Comment by bchiaruttini** [comment] 2021-04-30 12:49
Correct on behavior of Date Homestudy Completed form - should behave same way as SW.

**Comment by n-devr** [comment] 2021-04-30 17:25
Updated and ready to test in `develop`

**Comment by bchiaruttini** [comment] 2021-04-30 19:45
looks good.

**Closed** 2021-05-03 15:07 UTC
Labels: code enhancements, emails, forms, page updates, user accounts
