### ISSUE TITLE
Images Stored in Keystone not Rendering due to Error

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#301] opened 2019-08-14 19:35 UTC
Images attached to child records in Keystone are not rendering. When accessed the following error message is received:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>AFB914ECF7B75B9B</RequestId>
<HostId>
2stQGN8a7mX3lovjeaHvBpTsWrxorbZSi4Y+9Ovz6U72YeLnf5aeG9MvKM/M8MeOKeBZI55G5lY=
</HostId>
</Error>

A specific case example are images 3 & 4 for child #6628

@n-devr  reviewed the error and advises: 

I know there is a CDN that is being used to serve the images, so maybe that has special permissions to view the images and display them, but I am not familiar with that implementation

my guess is it's something to do with the connection between CloudFront and AWS

ASSIGNING TO JARED for review as he is familiar with the protocols for AWS

**Comment by joesmare** [comment] 2019-08-14 19:38
Update: It looks like it may be our old friend "the spacing issue". Jared can you run a script to clean this up? We recently migrated the all of the child photos and there are likely too many to manage individually.

**Comment by n-devr** [comment] 2019-08-17 20:43
It looks like the code that was put in place to remove whitespaces from filenames before they are uploaded is still in place and working properly.  The broken image links in this case were caused by the parentheses in the file names.

I'll implement a fix to the s3 upload service that will prevent all encoding of special characters (space, parentheses, etc.), which should fix the current issue and prevent other cases from popping up in the future.

After we verify the fix 'll coordinate with Jared to look into creating a script to find and fix the images with broken links.

**Comment by n-devr** [comment] 2019-08-29 17:39
As I'm working on a script to fix broken image links I'm finding more broken links than we originally thought.  For example: `https://d2oacar5fdyswm.cloudfront.net/children/images/attachments/6283_Ziy'maine_G._B._1-17__SAO-2017.jpg` 
This link contains no parentheses but is also not working.  I think in order to fix this completely we need to run a script that tests every single image URL and ensures that a valid image is returned, which is a much larger undertaking than the original scope of this work.

I will hold off on continuing down this rabbit hole until I consult with @joesmare and determine if this is worth the time and effort it will take.

**Comment by joesmare** [comment] 2019-11-19 14:18
So...our old friend "special characters" has reared it's ugly head again. This time it is the naming protocol for children with a special character in their name. It won't connect the image to the recond from AWS storage. The use case is:

Photo won't load from AWS -> Keystone interface due to child's name "Kiy'aa"  (#7294)

I know what's causing it, but here is the message that is displayed as a reminder:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>8CA9239A19CCBD10</RequestId>
<HostId>
464CQ/5okbh8GwQ8jy9j7Ik+zLeSFWduF0SVgz3Moy+Y44xGOmeFe9Wh7+CZJiODMeHRenVKPMA=
</HostId>
</Error>

@n-devr  please advise of what the final outcome was on this project. Looks like it was put on hold on 8/29. Did we ever get any feedback from @autoboxer on this issue?

**Comment by joesmare** [comment] 2019-11-20 14:39
RESOLUTION: In investigating the issue we looked at all the files in AWS and there are few cases where this was present before Noah updated the code (late-August). The fix is that any time a staff member encounters this error, we will send the use case to Noah and he will update the specific file.

**Comment by n-devr** [comment] 2019-11-20 18:49
Images updated for Kiy'aa and her brother Corey (7294, 7295) - all links are now working.

**Comment by bchiaruttini** [comment] 2020-05-01 10:49
Has not continued to present as an issue. Closing story.

**Closed by bchiaruttini** 2020-05-01 10:49 UTC
Labels: bug, model updates needed - production
