### ISSUE TITLE
Sibling Behavior ->AWS Image Impact

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#401] opened 2019-12-13 17:00 UTC
A new issue has been presented by the team related to conjoining siblings. HISTORY: two siblings who were being recruited for separately (two different records-not conjoined as siblings) were conjoined yesterday for the purpose or sibling recruitment. There were originally three siblings that had previously been part of a joint recruitment effort who had been conjoined as siblings in the past. Those records were decoupled when one sibling was matched. Until now the other two were being recruited for separately.

Notes from Emily Goldberger (CSC) about her actions:

Neveah and Nathaniel (7337 and 7336):
 
•         Originally recruited for as a sibling group of three with Natalia Vazquez (7338).
 
•         Natalia was taken off web. I created separate profiles for Neveah and Nathaniel with a photo of each (meaning the siblings were un-linked for recruitment)
 
•         Yesterday combined Neveah and Nathaniel’s profiles (re-linked for recruitment) and the individual photos stored in image attachments disappeared.

Since that time @jeremysMARE has restored the missing images from AWS. I would like for you to look at the specifics of this case to see if there is an obvious issue with the code associated with these actions, and if so, please try and debug it to prevent future issues of this nature.

**Comment by n-devr** [comment] 2019-12-18 19:06
I looked into this and could not find a root cause.  After speaking with @joesmare we're closing this for now, will track this behavior and if it occurs again we can reopen to investigate.

**Closed** 2019-12-18 19:06 UTC
Labels: removed - not an issue
